### ISSUE TITLE
Map event values to event display values

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#196] opened 2024-06-30 16:54 UTC
When we pull events from ER we may want to map the stored field values to the display values where there are defined 'choices'. This will require returning the json-schema for an event type and looking up the 'choice' display values for any field that is based on a choice.

**Comment by atmorling** [comment] 2024-07-03 13:57
@walljcg Closing this as I'm pretty sure it's a duplicate of #190

**Closed by atmorling** 2024-07-03 13:57 UTC
