### ISSUE TITLE
Overhaul ecoscope.io.utils.download_file()

### ISSUE THREAD

**Issue by walljcg** [wildlife-dynamics/ecoscope#78] opened 2024-03-05 09:03 UTC
The download_file() function needs to be expanded to support Dropbox urls, and GDrive urls. Let's look at using fsspec:. For example: 

with fsspec.open(url, mode='rt',) as file:
  config = json.loads(file.read())
config

**Comment by atmorling** [comment] 2024-03-18 17:31
Seems like the fsspec gdrive implementation [isn't released yet](https://github.com/fsspec/gdrivefs/issues/21) and so can't be pip installed.

Are we only concerned with supporting Dropbox and Gdrive?

**Comment by atmorling** [comment] 2024-04-08 14:23
Closing this as it's a duplicate of https://github.com/wildlife-dynamics/ecoscope/issues/96

**Closed by atmorling** 2024-04-08 14:23 UTC
Labels: ecoscope-core
