### ISSUE TITLE
Geopackages

### ISSUE THREAD

**Issue by Ankabedettidk** [wildlife-dynamics/ecoscope#4] opened 2022-09-22 10:22 UTC
Exporting trajectories using a gpkg always initiate the following errors when trying to open in Arcmap (this didn't happen in the past):

Invalid parameter value passed to function
main.APNR_all_quaterly_July-Sept2022_traj:  Invalid SQL syntax[near "-": syntax error]

Also trying to export it as shapefile doesn't work because of the ESRI date issue... 

What can I do :)

**Comment by walljcg** [comment] 2022-10-21 14:48
Sorry for the delay! The issue is that ESRI geodatabases (including shapefiles) won't accept certain characters in the column headings. To export for use in Esri it's best to clean up the column headings and change spaces, dashes  or other incompatible characters to underscores.  Something like this: `gdf.columns = [col.replace("-", "_").replace(" ", "_").replace(".", "_") for col in gdf.columns]`

**Comment by enlivn** [comment] 2023-10-27 20:02
Closing since this issue is over a year old. @Ankabedettidk please reopen if you still have questions.

**Closed by enlivn** 2023-10-27 20:02 UTC
